runtime: python
env: flex

entrypoint: gunicorn -b :$PORT --config=gunicorn_config.py app:api

beta_settings:
    cloud_sql_instances: office-map-208822:us-central1:officemap

runtime_config:
  python_version: 3
