"""updated location fields

Revision ID: 3e5c94ad92fd
Revises: b59e2d9acf6b
Create Date: 2017-09-21 19:36:44.145828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5c94ad92fd'
down_revision = 'b59e2d9acf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('colony_or_district', sa.String(), nullable=True))
    op.drop_column('location', 'colonyOrDistrict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('colonyOrDistrict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('location', 'colony_or_district')
    # ### end Alembic commands ###
