"""trip.user uselist=False

Revision ID: 4344b1c5760e
Revises: 51ff95d4e82a
Create Date: 2017-09-25 18:55:15.353292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4344b1c5760e'
down_revision = '51ff95d4e82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
