"""added uselist to trip.user relationship

Revision ID: 51ff95d4e82a
Revises: acfe2d4aaf05
Create Date: 2017-09-25 18:34:35.733527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ff95d4e82a'
down_revision = 'acfe2d4aaf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
