"""Added account table

Revision ID: 5700bbc38431
Revises: 
Create Date: 2017-09-17 19:52:30.387836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5700bbc38431'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth0_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_auth0_id'), 'user', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth0_id'), table_name='user')
    op.drop_column('user', 'auth0_id')
    # ### end Alembic commands ###
