"""added is_office column to location table

Revision ID: 59107eb54dcf
Revises: b1be5470b74d
Create Date: 2017-10-14 11:19:43.181643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59107eb54dcf'
down_revision = 'b1be5470b74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('is_office', sa.Boolean(), nullable=True))
    op.add_column('origin', sa.Column('is_office', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('origin', 'is_office')
    op.drop_column('destination', 'is_office')
    # ### end Alembic commands ###
