"""added project to space model

Revision ID: 817cb564c06a
Revises: ec4102d769e7
Create Date: 2018-05-20 10:06:08.794559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817cb564c06a'
down_revision = 'ec4102d769e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('project', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_space_project'), 'space', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_project'), table_name='space')
    op.drop_column('space', 'project')
    # ### end Alembic commands ###
