"""add office_id

Revision ID: 843f261c6790
Revises: ed3894d355fb
Create Date: 2018-04-22 11:54:00.639428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f261c6790'
down_revision = 'ed3894d355fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('office_id', sa.String(length=60), nullable=False))
    op.alter_column('space', 'owner_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space', 'owner_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('space', 'office_id')
    # ### end Alembic commands ###
