"""updated User field

Revision ID: a972c3c0156c
Revises: 3e5c94ad92fd
Create Date: 2017-09-21 19:44:14.334892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a972c3c0156c'
down_revision = '3e5c94ad92fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
