"""replace backref with back_populates in trip

Revision ID: acfe2d4aaf05
Revises: bc04edafa12a
Create Date: 2017-09-25 18:31:41.523279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfe2d4aaf05'
down_revision = 'bc04edafa12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
