"""updated trip field

Revision ID: b59e2d9acf6b
Revises: 32ba07a80dab
Create Date: 2017-09-21 19:23:01.473717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59e2d9acf6b'
down_revision = '32ba07a80dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('drive_or_ride', sa.String(), nullable=False))
    op.drop_column('trip', 'driveOrRide')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('driveOrRide', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trip', 'drive_or_ride')
    # ### end Alembic commands ###
