"""remove ForeignKey from relationship in trip data model

Revision ID: bc04edafa12a
Revises: a972c3c0156c
Create Date: 2017-09-25 18:30:09.966166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc04edafa12a'
down_revision = 'a972c3c0156c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
