"""streetNumber to street_number in location

Revision ID: e441bb74526d
Revises: 9431b0218c38
Create Date: 2017-09-26 19:49:00.403312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e441bb74526d'
down_revision = '9431b0218c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('street_number', sa.String(), nullable=True))
    op.drop_column('destination', 'streetNumber')
    op.add_column('origin', sa.Column('street_number', sa.String(), nullable=True))
    op.drop_column('origin', 'streetNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('origin', sa.Column('streetNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('origin', 'street_number')
    op.add_column('destination', sa.Column('streetNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('destination', 'street_number')
    # ### end Alembic commands ###
