"""added project to space model

Revision ID: ec4102d769e7
Revises: 843f261c6790
Create Date: 2018-05-20 10:04:30.412922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4102d769e7'
down_revision = '843f261c6790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
