"""removed trips relationship

Revision ID: ed3894d355fb
Revises: d0207d93e777
Create Date: 2018-04-21 17:12:11.818324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3894d355fb'
down_revision = 'd0207d93e777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
